spring.datasource.url: jdbc:postgresql://localhost:5432/leagueTest?serverTimezone=UTC
spring.datasource.username: postgres
spring.datasource.password: qwertyui
spring.jpa.hibernate.ddl-auto: update
spring.jpa.show-sql: true

fileName.value: C://users/phil/desktop/file.csv
